GET http://localhost:8080/api/alert

###
POST http://localhost:8080/api/alert
content-type: application/json

{
  "migrationId":"{{$guid}}",
  "volumes": ["vol1","vol2","vol3"], 
  "Alerttype":"mail",
  "MigrationDate": "{{$datetime 'YYYY-MM-DD' 2 d}}T00:00:00Z",
  "isreadytosend": true
}

###
PATCH http://localhost:8080/api/alert


###
DELETE http://localhost:8080/api/alert