GET http://localhost:8080/api/alerts

###
POST http://localhost:8080/api/alert
content-type: application/json

{
  "migrationId":"{{$guid}}",
  "volumes": ["vol1","vol2"], 
  "alertType":"email",
  "migrationDate": "{{$datetime 'YYYY-MM-DD' 4 d}}T00:00:00Z",
  "isReadyToSend": true,
  "distributionList": ["ab30342@citi.com"]
}

###
PATCH http://localhost:8080/api/alert/66b5d084d10e0c734d9f5937
Content-Type: application/json

{
   "volumes": ["vol1","vol6"],   
  "migrationDate": "{{$datetime 'YYYY-MM-DD' 2 d}}T00:00:00Z"  
}

###
DELETE http://localhost:8080/api/alert/66b5c56f2e7f5e82e5954167


#######################################################################################################################################

####
GET http://localhost:8080/api/jobs

#####

POST http://localhost:8080/api/job
content-type: application/json

{
  "cronExpression":"*/1 * * * *",
  "comments": "Alert every 1 minute", 
  "startDate":1,
  "endDate": 6,
  "templateName": "simple.page.tmpl",
  "addedBy":"ab30342",
  "mailSubject": "Your migration is approaching"
}

###
PATCH http://localhost:8080/api/job/66b5d0c7d10e0c734d9f5939
Content-Type: application/json

{  
  "addedBy":"Adarsh"
}

###
DELETE http://localhost:8080/api/job/66b5d0dfd10e0c734d9f593b