# @name alerts
GET http://localhost:8081/api/alerts
# GET http://localhost:8081/api/alerts?startDate=2024-08-21&endDate=2024-08-24

@migrationId = {{alerts.response.body.0.migrationId}}

###
# @name createAlert
POST http://localhost:8081/api/alert
content-type: application/json

{
  "migrationId":"{{$guid}}",
  "volumes": ["vol1","vol12"], 
  "alertType":"email",
  "migrationDate": "{{$datetime 'YYYY-MM-DD' 4 d}}T00:00:00Z",
  "isReadyToSend": true,
  "distributionList": ["ab30342@citi.com"]
}

###

#@migrationId = {{createAlert.response.body.$.migrationId}}

###
GET http://localhost:8081/api/alert/{{migrationId}}

###
POST http://localhost:8081/api/alert/notifyDateChange/{{migrationId}}
Content-Type: application/json

{
  "newMigrationDate": "{{$datetime 'YYYY-MM-DD' 10 d}}T00:00:00Z",
  "isReadyToSend": false
}


####
PATCH http://localhost:8081/api/alert/{{migrationId}}
Content-Type: application/json

{
  "volumes": ["vol1","vol4"],  
  "migrationDate": "{{$datetime 'YYYY-MM-DD' 5 d}}T00:00:00Z"  
}

###
PATCH http://localhost:8081/api/alert/{{migrationId}}?isApproved=true
Content-Type: application/json

{
  "isReadyToSend": true,
  "migrationDate": "{{$datetime 'YYYY-MM-DD' 10 d}}T00:00:00Z" 
}

###
PATCH http://localhost:8081/api/alert/{{migrationId}}?isApproved=false
Content-Type: application/json

{
  "isReadyToSend": true
}

###
DELETE http://localhost:8081/api/alert/{{migrationId}}


#######################################################################################################################################

# @name jobs
GET http://localhost:8081/api/jobs

@jobId = {{jobs.response.body.0._id}}

#####
# @name createJob
POST http://localhost:8081/api/job
content-type: application/json

{
  "cronExpression":"*/1 * * * *",
  "comments": "Alert every 1 minute", 
  "startDate":1,
  "endDate": 6,
  "templateName": "warning.page.tmpl",
  "addedBy":"ab30342",
  "mailSubject": "Your migration is approaching"
}

# @jobId = {{createJob.response.body.$._id}}


###
GET http://localhost:8081/api/job/{{jobId}}

###
PATCH http://localhost:8081/api/job/{{jobId}}
Content-Type: application/json

{  
  "addedBy":"adarsh"
}

###
DELETE http://localhost:8081/api/job/{{jobId}}